"""
Page 147 — Proactive AI / Intent Engine
=========================================
Inspired by the vision: instead of waiting for you to type a prompt, this page
collects behavioral signals from across the entire app, builds a real-time
understanding of your current context and intent, and proactively surfaces
insights, warnings, and recommendations — before you ask.

Core concepts implemented:
  • Behavioral Signal Pipelines  — structured data from budget, todos, notes,
                                    creator content, SoleOps, spending patterns
  • Intent-Aware Agent           — Claude analyzes all signals, infers focus,
                                    surfaces what you probably need right now
  • Personalization Layer        — user profile that evolves over time,
                                    learns your patterns, leads rather than waits
  • Context Injection            — manual context notes feed directly into the
                                    AI's reasoning window
"""

import json
import re
import streamlit as st
import pandas as pd
from datetime import datetime, date, timedelta
from utils.db import get_conn, init_db, execute, get_setting, set_setting
from utils.auth import (
    require_login, render_sidebar_brand, render_sidebar_user_widget, inject_css
)

# ── Page Config ───────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="Proactive AI — Peach State Savings",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="auto",
)
init_db()
inject_css()
require_login()

# ── Sidebar ───────────────────────────────────────────────────────────────────

render_sidebar_brand()
st.sidebar.markdown("---")
st.sidebar.page_link("app.py",                            label="Overview",           icon="📊")
st.sidebar.page_link("pages/22_todo.py",                  label="✅ Todo",            icon="✅")
st.sidebar.page_link("pages/24_creator_companion.py",     label="🎬 Creator",         icon="🎬")
st.sidebar.page_link("pages/25_notes.py",                 label="📝 Notes",           icon="📝")
st.sidebar.page_link("pages/26_media_library.py",         label="🎵 Media Library",   icon="🎵")
st.sidebar.page_link("pages/17_personal_assistant.py",    label="Personal Assistant", icon="🤖")
st.sidebar.page_link("pages/147_proactive_ai_engine.py",  label="🧠 Proactive AI",    icon="🧠")
render_sidebar_user_widget()

# ── DB Setup ──────────────────────────────────────────────────────────────────

USE_POSTGRES = bool(get_setting("use_postgres", ""))
PH = "%s" if USE_POSTGRES else "?"


def _ensure_tables():
    """Create all tables for the Proactive AI engine."""
    conn = get_conn()

    # Behavioral signals captured from every source in the app
    execute(conn, f"""
        CREATE TABLE IF NOT EXISTS intent_signals (
            id          INTEGER PRIMARY KEY {'SERIAL' if USE_POSTGRES else 'AUTOINCREMENT'},
            user_id     INTEGER DEFAULT 0,
            signal_type TEXT NOT NULL,
            source      TEXT NOT NULL,
            label       TEXT,
            value       REAL DEFAULT 0,
            content     TEXT,
            weight      REAL DEFAULT 1.0,
            captured_at TEXT DEFAULT (datetime('now'))
        )
    """.replace("INTEGER PRIMARY KEY SERIAL", "SERIAL PRIMARY KEY"))

    # Proactive insights generated by the AI
    execute(conn, f"""
        CREATE TABLE IF NOT EXISTS proactive_insights (
            id              INTEGER PRIMARY KEY {'SERIAL' if USE_POSTGRES else 'AUTOINCREMENT'},
            user_id         INTEGER DEFAULT 0,
            insight_type    TEXT,
            title           TEXT,
            body            TEXT,
            priority        TEXT DEFAULT 'normal',
            source_signals  TEXT,
            feedback        TEXT,
            dismissed       INTEGER DEFAULT 0,
            created_at      TEXT DEFAULT (datetime('now'))
        )
    """.replace("INTEGER PRIMARY KEY SERIAL", "SERIAL PRIMARY KEY"))

    # Manual context notes the user injects into the AI's reasoning window
    execute(conn, f"""
        CREATE TABLE IF NOT EXISTS intent_context_notes (
            id          INTEGER PRIMARY KEY {'SERIAL' if USE_POSTGRES else 'AUTOINCREMENT'},
            user_id     INTEGER DEFAULT 0,
            content     TEXT NOT NULL,
            pinned      INTEGER DEFAULT 0,
            created_at  TEXT DEFAULT (datetime('now'))
        )
    """.replace("INTEGER PRIMARY KEY SERIAL", "SERIAL PRIMARY KEY"))

    # User's personalization profile — AI-extracted goals, values, patterns
    execute(conn, f"""
        CREATE TABLE IF NOT EXISTS intent_profile (
            id          INTEGER PRIMARY KEY {'SERIAL' if USE_POSTGRES else 'AUTOINCREMENT'},
            user_id     INTEGER DEFAULT 0,
            key         TEXT NOT NULL,
            value       TEXT,
            confidence  REAL DEFAULT 0.7,
            updated_at  TEXT DEFAULT (datetime('now')),
            UNIQUE(user_id, key)
        )
    """.replace("INTEGER PRIMARY KEY SERIAL", "SERIAL PRIMARY KEY").replace(
        "UNIQUE(user_id, key)", "UNIQUE(user_id, key)"
    ))

    conn.commit()
    conn.close()


_ensure_tables()

# ── Constants ─────────────────────────────────────────────────────────────────

SIGNAL_TYPES = {
    "finance":   ("💰", "#f39c12"),
    "todo":      ("✅", "#27ae60"),
    "notes":     ("📝", "#3498db"),
    "creator":   ("🎬", "#9b59b6"),
    "soleops":   ("👟", "#e74c3c"),
    "context":   ("🧩", "#1abc9c"),
    "pattern":   ("📈", "#e67e22"),
}

INSIGHT_ICONS = {
    "alert":      "🚨",
    "focus":      "🎯",
    "pattern":    "📈",
    "opportunity":"💡",
    "reminder":   "⏰",
    "financial":  "💰",
    "creative":   "🎬",
    "career":     "🏢",
}


# ── Helpers: API ──────────────────────────────────────────────────────────────

def _get_api_key() -> str:
    if st.session_state.get("api_key"):
        return st.session_state["api_key"]
    key = get_setting("anthropic_api_key", "")
    if key:
        st.session_state["api_key"] = key
    return key


def _call_claude(prompt: str, max_tokens: int = 2048) -> str:
    api_key = _get_api_key()
    if not api_key:
        raise ValueError("No Claude API key. Add it in Settings.")
    import anthropic
    client = anthropic.Anthropic(api_key=api_key)
    msg = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=max_tokens,
        messages=[{"role": "user", "content": prompt}],
    )
    return msg.content[0].text.strip()


# ── Helpers: Signal Collection ────────────────────────────────────────────────

def _collect_finance_signals(uid: int) -> list[dict]:
    """Pull spending patterns and budget signals."""
    signals = []
    conn = get_conn()
    try:
        today = date.today()
        this_month = today.strftime("%Y-%m")
        last_month = (today.replace(day=1) - timedelta(days=1)).strftime("%Y-%m")

        # This month's spending by category
        rows = execute(conn, f"""
            SELECT category, SUM(actual) as total
            FROM expenses
            WHERE month = {PH}
            GROUP BY category
            ORDER BY total DESC
        """, (this_month,)).fetchall()

        for r in rows:
            cat, total = r[0], r[1] or 0
            if total > 0:
                signals.append({
                    "signal_type": "finance",
                    "source": "budget",
                    "label": f"Spent ${total:,.0f} in {cat} this month",
                    "value": total,
                    "content": json.dumps({"category": cat, "amount": total, "month": this_month}),
                    "weight": min(2.0, total / 200),
                })

        # Income vs spend gap
        income_row = execute(conn, f"""
            SELECT SUM(amount) FROM income WHERE month = {PH}
        """, (this_month,)).fetchone()
        income = (income_row[0] or 0) if income_row else 0

        total_spend = sum(s["value"] for s in signals if s["signal_type"] == "finance")
        if income > 0:
            gap = income - total_spend
            signals.append({
                "signal_type": "finance",
                "source": "budget",
                "label": f"Remaining budget: ${gap:,.0f} of ${income:,.0f} income",
                "value": gap,
                "content": json.dumps({"income": income, "spent": total_spend, "remaining": gap, "month": this_month}),
                "weight": 1.5,
            })

        # Month-over-month spend change
        last_rows = execute(conn, f"""
            SELECT SUM(actual) FROM expenses WHERE month = {PH}
        """, (last_month,)).fetchone()
        last_total = (last_rows[0] or 0) if last_rows else 0

        if last_total > 0 and total_spend > 0:
            pct = ((total_spend - last_total) / last_total) * 100
            direction = "up" if pct > 0 else "down"
            signals.append({
                "signal_type": "pattern",
                "source": "budget",
                "label": f"Spending {direction} {abs(pct):.0f}% vs last month",
                "value": pct,
                "content": json.dumps({"this_month": total_spend, "last_month": last_total, "change_pct": pct}),
                "weight": 1.8 if abs(pct) > 15 else 0.8,
            })

        # Expenses with no projected amount (unplanned)
        unplanned = execute(conn, f"""
            SELECT COUNT(*) FROM expenses
            WHERE month = {PH} AND (projected IS NULL OR projected = 0) AND actual > 0
        """, (this_month,)).fetchone()
        if unplanned and unplanned[0] > 0:
            signals.append({
                "signal_type": "finance",
                "source": "budget",
                "label": f"{unplanned[0]} unplanned expense(s) logged this month",
                "value": unplanned[0],
                "content": json.dumps({"count": unplanned[0]}),
                "weight": 1.2,
            })

    except Exception:
        pass
    finally:
        conn.close()
    return signals


def _collect_todo_signals(uid: int) -> list[dict]:
    """Pull task patterns and urgency signals."""
    signals = []
    conn = get_conn()
    try:
        today_str = date.today().isoformat()
        tomorrow_str = (date.today() + timedelta(days=1)).isoformat()
        week_str = (date.today() + timedelta(days=7)).isoformat()

        # Overdue tasks
        overdue = execute(conn, f"""
            SELECT id, title, due_date, priority FROM pa_tasks
            WHERE status = 'open' AND due_date IS NOT NULL AND due_date < {PH}
            ORDER BY due_date ASC
        """, (today_str,)).fetchall()

        for row in overdue:
            signals.append({
                "signal_type": "todo",
                "source": "tasks",
                "label": f"OVERDUE: {row[1][:60]} (due {row[2]})",
                "value": -1,
                "content": json.dumps({"id": row[0], "title": row[1], "due": row[2], "priority": row[3]}),
                "weight": 3.0 if row[3] == "high" else 2.0,
            })

        # Due today or tomorrow
        due_soon = execute(conn, f"""
            SELECT id, title, due_date, priority FROM pa_tasks
            WHERE status = 'open' AND due_date BETWEEN {PH} AND {PH}
            ORDER BY due_date ASC
        """, (today_str, tomorrow_str)).fetchall()

        for row in due_soon:
            signals.append({
                "signal_type": "todo",
                "source": "tasks",
                "label": f"Due soon: {row[1][:60]} ({row[2]})",
                "value": 0,
                "content": json.dumps({"id": row[0], "title": row[1], "due": row[2], "priority": row[3]}),
                "weight": 2.5 if row[3] == "high" else 1.5,
            })

        # High priority open tasks
        high_prio = execute(conn, f"""
            SELECT COUNT(*) FROM pa_tasks
            WHERE status = 'open' AND priority = 'high'
        """).fetchone()
        if high_prio and high_prio[0] > 0:
            signals.append({
                "signal_type": "todo",
                "source": "tasks",
                "label": f"{high_prio[0]} high-priority task(s) open",
                "value": high_prio[0],
                "content": json.dumps({"count": high_prio[0]}),
                "weight": 1.8,
            })

        # Completion rate (last 30 days)
        done_30 = execute(conn, f"""
            SELECT COUNT(*) FROM pa_tasks
            WHERE status = 'done'
            AND completed_at >= datetime('now', '-30 days')
        """).fetchone()
        created_30 = execute(conn, f"""
            SELECT COUNT(*) FROM pa_tasks
            WHERE created_at >= datetime('now', '-30 days')
        """).fetchone()
        done_n = done_30[0] if done_30 else 0
        created_n = created_30[0] if created_30 else 0
        if created_n > 0:
            rate = (done_n / created_n) * 100
            signals.append({
                "signal_type": "pattern",
                "source": "tasks",
                "label": f"Task completion rate: {rate:.0f}% over last 30 days",
                "value": rate,
                "content": json.dumps({"done": done_n, "created": created_n, "rate": rate}),
                "weight": 0.8,
            })

        # Total open task count
        open_count = execute(conn, f"""
            SELECT COUNT(*) FROM pa_tasks WHERE status = 'open'
        """).fetchone()
        if open_count and open_count[0] > 0:
            signals.append({
                "signal_type": "todo",
                "source": "tasks",
                "label": f"{open_count[0]} total open tasks",
                "value": open_count[0],
                "content": json.dumps({"count": open_count[0]}),
                "weight": 0.5 + min(1.5, open_count[0] / 10),
            })

    except Exception:
        pass
    finally:
        conn.close()
    return signals


def _collect_notes_signals(uid: int) -> list[dict]:
    """Pull notes activity and topic signals."""
    signals = []
    conn = get_conn()
    try:
        # Recent notes (last 7 days)
        recent = execute(conn, f"""
            SELECT title, category, tags, updated_at FROM notes
            WHERE updated_at >= datetime('now', '-7 days')
            ORDER BY updated_at DESC
            LIMIT 10
        """).fetchall()

        if recent:
            topics = [r[0] for r in recent if r[0]]
            signals.append({
                "signal_type": "notes",
                "source": "notes",
                "label": f"Active in Notes: {', '.join(topics[:4])}",
                "value": len(recent),
                "content": json.dumps({"recent_notes": [r[0] for r in recent], "count": len(recent)}),
                "weight": 0.7,
            })

        # Notes with no category (potential clutter)
        uncategorized = execute(conn, f"""
            SELECT COUNT(*) FROM notes
            WHERE (category IS NULL OR category = '') AND archived = 0
        """).fetchone()
        if uncategorized and uncategorized[0] > 3:
            signals.append({
                "signal_type": "notes",
                "source": "notes",
                "label": f"{uncategorized[0]} uncategorized notes (possible clutter)",
                "value": uncategorized[0],
                "content": json.dumps({"count": uncategorized[0]}),
                "weight": 0.5,
            })

        # Total notes for context
        total_notes = execute(conn, "SELECT COUNT(*) FROM notes WHERE archived = 0").fetchone()
        if total_notes and total_notes[0] > 0:
            signals.append({
                "signal_type": "notes",
                "source": "notes",
                "label": f"Notes library: {total_notes[0]} active notes",
                "value": total_notes[0],
                "content": json.dumps({"total": total_notes[0]}),
                "weight": 0.3,
            })

    except Exception:
        pass
    finally:
        conn.close()
    return signals


def _collect_creator_signals(uid: int) -> list[dict]:
    """Pull creator content pipeline signals."""
    signals = []
    conn = get_conn()
    try:
        today_str = date.today().isoformat()
        week_str = (date.today() + timedelta(days=7)).isoformat()

        # Content due this week
        due_content = execute(conn, f"""
            SELECT title, channel_id, status, publish_date FROM cc_content
            WHERE status != 'published'
            AND publish_date IS NOT NULL
            AND publish_date <= {PH}
            ORDER BY publish_date ASC
            LIMIT 10
        """, (week_str,)).fetchall()

        for row in due_content:
            overdue = row[3] and row[3] < today_str
            label = f"{'OVERDUE' if overdue else 'Due'} content: {row[0][:50]} ({row[3]})"
            signals.append({
                "signal_type": "creator",
                "source": "creator_companion",
                "label": label,
                "value": -1 if overdue else 0,
                "content": json.dumps({"title": row[0], "status": row[2], "due": row[3]}),
                "weight": 2.5 if overdue else 1.5,
            })

        # Content in draft (stalled)
        drafts = execute(conn, f"""
            SELECT COUNT(*) FROM cc_content WHERE status = 'draft'
        """).fetchone()
        if drafts and drafts[0] > 0:
            signals.append({
                "signal_type": "creator",
                "source": "creator_companion",
                "label": f"{drafts[0]} content draft(s) stalled / not published",
                "value": drafts[0],
                "content": json.dumps({"draft_count": drafts[0]}),
                "weight": 1.0,
            })

        # Idea backlog
        ideas = execute(conn, f"""
            SELECT COUNT(*) FROM cc_ideas WHERE status = 'new'
        """).fetchone()
        if ideas and ideas[0] > 0:
            signals.append({
                "signal_type": "creator",
                "source": "creator_companion",
                "label": f"{ideas[0]} content idea(s) in backlog",
                "value": ideas[0],
                "content": json.dumps({"idea_count": ideas[0]}),
                "weight": 0.6,
            })

    except Exception:
        pass
    finally:
        conn.close()
    return signals


def _collect_soleops_signals(uid: int) -> list[dict]:
    """Pull SoleOps inventory and sales signals."""
    signals = []
    conn = get_conn()
    try:
        # Stale inventory (listed > 60 days, unsold)
        stale = execute(conn, f"""
            SELECT COUNT(*), SUM(buy_price) FROM soleops_inventory
            WHERE status = 'listed'
            AND listed_date <= date('now', '-60 days')
        """).fetchone()
        if stale and stale[0] and stale[0] > 0:
            tied_up = stale[1] or 0
            signals.append({
                "signal_type": "soleops",
                "source": "soleops_inventory",
                "label": f"{stale[0]} item(s) listed 60+ days — ${tied_up:,.0f} capital tied up",
                "value": tied_up,
                "content": json.dumps({"stale_count": stale[0], "capital": tied_up}),
                "weight": 2.0,
            })

        # Total active inventory value
        inventory = execute(conn, f"""
            SELECT COUNT(*), SUM(buy_price) FROM soleops_inventory
            WHERE status IN ('listed', 'in_stock')
        """).fetchone()
        if inventory and inventory[0] and inventory[0] > 0:
            signals.append({
                "signal_type": "soleops",
                "source": "soleops_inventory",
                "label": f"SoleOps: {inventory[0]} item(s) active, ${(inventory[1] or 0):,.0f} inventory value",
                "value": inventory[1] or 0,
                "content": json.dumps({"count": inventory[0], "value": inventory[1] or 0}),
                "weight": 0.8,
            })

        # Recent sales (last 7 days)
        recent_sales = execute(conn, f"""
            SELECT COUNT(*), SUM(sale_price) FROM soleops_inventory
            WHERE status = 'sold'
            AND sold_date >= date('now', '-7 days')
        """).fetchone()
        if recent_sales and recent_sales[0] and recent_sales[0] > 0:
            revenue = recent_sales[1] or 0
            signals.append({
                "signal_type": "soleops",
                "source": "soleops_inventory",
                "label": f"SoleOps: {recent_sales[0]} sale(s) this week — ${revenue:,.0f} revenue",
                "value": revenue,
                "content": json.dumps({"sales": recent_sales[0], "revenue": revenue}),
                "weight": 1.2,
            })

    except Exception:
        pass
    finally:
        conn.close()
    return signals


def _collect_all_signals(uid: int) -> list[dict]:
    """Collect behavioral signals from all sources in the app."""
    all_signals = []
    all_signals.extend(_collect_finance_signals(uid))
    all_signals.extend(_collect_todo_signals(uid))
    all_signals.extend(_collect_notes_signals(uid))
    all_signals.extend(_collect_creator_signals(uid))
    all_signals.extend(_collect_soleops_signals(uid))

    # Add manual context notes
    conn = get_conn()
    try:
        ctx_notes = execute(conn, f"""
            SELECT content, pinned FROM intent_context_notes
            WHERE user_id = {PH}
            ORDER BY pinned DESC, created_at DESC
            LIMIT 10
        """, (uid,)).fetchall()
        for row in ctx_notes:
            all_signals.append({
                "signal_type": "context",
                "source": "manual",
                "label": row[0][:80],
                "value": 1,
                "content": json.dumps({"note": row[0], "pinned": bool(row[1])}),
                "weight": 2.0 if row[1] else 1.0,
            })
    except Exception:
        pass
    finally:
        conn.close()

    return all_signals


# ── Helpers: Profile ──────────────────────────────────────────────────────────

def _get_profile(uid: int) -> dict:
    conn = get_conn()
    try:
        rows = execute(conn, f"""
            SELECT key, value, confidence, updated_at FROM intent_profile
            WHERE user_id = {PH}
            ORDER BY confidence DESC
        """, (uid,)).fetchall()
        return {r[0]: {"value": r[1], "confidence": r[2], "updated_at": r[3]} for r in rows}
    except Exception:
        return {}
    finally:
        conn.close()


def _set_profile_key(uid: int, key: str, value: str, confidence: float = 0.8):
    conn = get_conn()
    try:
        if USE_POSTGRES:
            execute(conn, f"""
                INSERT INTO intent_profile (user_id, key, value, confidence, updated_at)
                VALUES ({PH},{PH},{PH},{PH},{PH})
                ON CONFLICT (user_id, key) DO UPDATE
                SET value={PH}, confidence={PH}, updated_at={PH}
            """, (uid, key, value, confidence, datetime.now().isoformat(),
                  value, confidence, datetime.now().isoformat()))
        else:
            execute(conn, f"""
                INSERT OR REPLACE INTO intent_profile (user_id, key, value, confidence, updated_at)
                VALUES ({PH},{PH},{PH},{PH},{PH})
            """, (uid, key, value, confidence, datetime.now().isoformat()))
        conn.commit()
    except Exception:
        pass
    finally:
        conn.close()


def _save_insight(uid: int, insight_type: str, title: str, body: str,
                  priority: str = "normal", source_signals: str = "") -> int:
    conn = get_conn()
    try:
        cursor = execute(conn, f"""
            INSERT INTO proactive_insights
            (user_id, insight_type, title, body, priority, source_signals)
            VALUES ({PH},{PH},{PH},{PH},{PH},{PH})
        """, (uid, insight_type, title, body, priority, source_signals))
        conn.commit()
        return cursor.lastrowid or 0
    except Exception:
        return 0
    finally:
        conn.close()


def _get_insights(uid: int, limit: int = 20) -> list[dict]:
    conn = get_conn()
    try:
        rows = execute(conn, f"""
            SELECT id, insight_type, title, body, priority, feedback, dismissed, created_at
            FROM proactive_insights
            WHERE user_id = {PH} AND dismissed = 0
            ORDER BY
                CASE priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2
                              WHEN 'normal' THEN 3 ELSE 4 END,
                created_at DESC
            LIMIT {PH}
        """, (uid, limit)).fetchall()
        return [
            {
                "id": r[0], "insight_type": r[1], "title": r[2], "body": r[3],
                "priority": r[4], "feedback": r[5], "dismissed": r[6], "created_at": r[7]
            }
            for r in rows
        ]
    except Exception:
        return []
    finally:
        conn.close()


def _feedback_insight(insight_id: int, feedback: str):
    conn = get_conn()
    try:
        execute(conn, f"""
            UPDATE proactive_insights SET feedback = {PH} WHERE id = {PH}
        """, (feedback, insight_id))
        conn.commit()
    except Exception:
        pass
    finally:
        conn.close()


def _dismiss_insight(insight_id: int):
    conn = get_conn()
    try:
        execute(conn, f"""
            UPDATE proactive_insights SET dismissed = 1 WHERE id = {PH}
        """, (insight_id,))
        conn.commit()
    except Exception:
        pass
    finally:
        conn.close()


# ── Helpers: AI Analysis ──────────────────────────────────────────────────────

def _build_signal_context(signals: list[dict]) -> str:
    """Format signals as structured context for the LLM."""
    by_type: dict[str, list] = {}
    for s in sorted(signals, key=lambda x: -x.get("weight", 1.0)):
        t = s["signal_type"]
        if t not in by_type:
            by_type[t] = []
        by_type[t].append(s)

    lines = []
    type_names = {
        "finance":   "FINANCIAL SIGNALS",
        "todo":      "TASK / PRODUCTIVITY SIGNALS",
        "notes":     "NOTES ACTIVITY",
        "creator":   "CONTENT CREATION PIPELINE",
        "soleops":   "RESALE BUSINESS (SOLEOPS)",
        "context":   "USER-INJECTED CONTEXT",
        "pattern":   "BEHAVIORAL PATTERNS",
    }

    for t, t_name in type_names.items():
        if t in by_type:
            lines.append(f"\n## {t_name}")
            for s in by_type[t][:8]:   # cap per category
                weight_note = f" [weight: {s['weight']:.1f}]" if s["weight"] > 1.5 else ""
                lines.append(f"  • {s['label']}{weight_note}")

    return "\n".join(lines)


def _run_proactive_analysis(signals: list[dict], profile: dict, uid: int) -> list[dict]:
    """Send all signals to Claude and get structured proactive insights back."""
    signal_context = _build_signal_context(signals)
    today = datetime.now()

    profile_lines = []
    for k, v in profile.items():
        profile_lines.append(f"  • {k}: {v['value']} (confidence: {v['confidence']:.0%})")
    profile_str = "\n".join(profile_lines) if profile_lines else "  (no profile data yet)"

    prompt = f"""You are an intent-aware AI assistant for Darrian Belcher, TPM at Visa with an MSDA, homelab builder, reseller (SoleOps), and content creator.

Today: {today.strftime('%A, %B %d, %Y at %I:%M %p')}

Your job is NOT to answer a question — your job is to proactively analyze Darrian's behavioral signals and surface what he actually needs right now, before he even asks.

## USER PROFILE (learned over time)
{profile_str}

## LIVE BEHAVIORAL SIGNALS (collected from across the app)
{signal_context}

## YOUR TASK
Generate 4–7 proactive insights in JSON format. Each insight should:
- Be specific and actionable (reference exact data from the signals)
- Be prioritized correctly (critical > high > normal > low)
- Come from the perspective of a hyper-attentive chief of staff who knows everything about Darrian's life
- NOT be generic — every insight must be grounded in the actual signal data

Return ONLY valid JSON, no other text:
{{
  "insights": [
    {{
      "type": "alert|focus|pattern|opportunity|reminder|financial|creative|career",
      "title": "Short headline (max 60 chars)",
      "body": "2–4 sentences. Specific. Actionable. Reference real numbers/data.",
      "priority": "critical|high|normal|low",
      "action": "One-line recommended action"
    }}
  ],
  "current_focus": "1 sentence — what does the data say Darrian is primarily focused on right now?",
  "blind_spot": "1 sentence — what is he likely NOT thinking about that he should be?",
  "energy_allocation": {{
    "finance": 0–100,
    "productivity": 0–100,
    "creator": 0–100,
    "soleops": 0–100,
    "personal": 0–100
  }}
}}

Make every insight feel like it came from someone who has been watching closely and genuinely wants Darrian to win."""

    raw = _call_claude(prompt, max_tokens=3000)

    # Strip markdown fences if present
    raw = re.sub(r"```(?:json)?\s*", "", raw).strip().rstrip("`")
    m = re.search(r"\{.*\}", raw, re.DOTALL)
    if not m:
        raise ValueError("AI did not return valid JSON")

    data = json.loads(m.group(0))

    # Save insights to DB
    saved = []
    for ins in data.get("insights", []):
        ins_id = _save_insight(
            uid=uid,
            insight_type=ins.get("type", "focus"),
            title=ins.get("title", ""),
            body=ins.get("body", "") + (f"\n\n**→ {ins['action']}**" if ins.get("action") else ""),
            priority=ins.get("priority", "normal"),
            source_signals=json.dumps([s["label"] for s in signals[:10]]),
        )
        ins["id"] = ins_id
        saved.append(ins)

    # Save meta to session
    st.session_state["intent_focus"] = data.get("current_focus", "")
    st.session_state["intent_blind_spot"] = data.get("blind_spot", "")
    st.session_state["intent_energy"] = data.get("energy_allocation", {})

    # Update profile with inferred focus
    if data.get("current_focus"):
        _set_profile_key(uid, "current_focus", data["current_focus"], confidence=0.9)
    if data.get("blind_spot"):
        _set_profile_key(uid, "latest_blind_spot", data["blind_spot"], confidence=0.8)

    return saved


def _run_intent_update(signals: list[dict], profile: dict, uid: int) -> str:
    """Ask Claude to update the user's intent profile from signals."""
    signal_context = _build_signal_context(signals)

    prompt = f"""Analyze these behavioral signals and extract structured facts about this user's goals, patterns, and intent.

## BEHAVIORAL SIGNALS
{signal_context}

## CURRENT PROFILE
{json.dumps({k: v['value'] for k, v in profile.items()}, indent=2)}

Return ONLY valid JSON:
{{
  "profile_updates": [
    {{"key": "string", "value": "string", "confidence": 0.0–1.0}}
  ]
}}

Keys to consider:
- primary_income_focus (main financial concern)
- top_productivity_area (where most tasks cluster)
- creative_pipeline_health (healthy/stalled/overloaded)
- soleops_momentum (active/slow/stale)
- financial_health_trend (improving/stable/concerning)
- biggest_bottleneck (single biggest constraint right now)
- estimated_weekly_bandwidth (how stretched are they?)

Only include keys where you have reasonable signal-backed confidence."""

    raw = _call_claude(prompt, max_tokens=1200)
    raw = re.sub(r"```(?:json)?\s*", "", raw).strip().rstrip("`")
    m = re.search(r"\{.*\}", raw, re.DOTALL)
    if not m:
        return "No profile updates extracted."

    data = json.loads(m.group(0))
    updates = data.get("profile_updates", [])
    for u in updates:
        _set_profile_key(uid, u["key"], u["value"], u.get("confidence", 0.7))

    return f"Updated {len(updates)} profile key(s): {', '.join(u['key'] for u in updates)}"


# ── Tab Renderers ─────────────────────────────────────────────────────────────

def _render_dashboard_tab(uid: int, signals: list[dict]):
    """Main intent dashboard — the proactive briefing."""

    # Top hero strip
    focus = st.session_state.get("intent_focus", "")
    blind_spot = st.session_state.get("intent_blind_spot", "")
    energy = st.session_state.get("intent_energy", {})

    col_run, col_status = st.columns([2, 3])
    with col_run:
        if st.button("⚡ Run Proactive Analysis", type="primary",
                     use_container_width=True, key="btn_run_analysis"):
            api_key = _get_api_key()
            if not api_key:
                st.error("No Claude API key. Add it in the ⚙️ Settings tab.")
            else:
                with st.spinner("🧠 Collecting signals and analyzing intent..."):
                    try:
                        profile = _get_profile(uid)
                        new_insights = _run_proactive_analysis(signals, profile, uid)
                        st.session_state["last_analysis_time"] = datetime.now().strftime("%I:%M %p")
                        st.session_state["last_insight_count"] = len(new_insights)
                        st.success(f"Generated {len(new_insights)} proactive insights!")
                        st.rerun()
                    except Exception as e:
                        st.error(f"Analysis failed: {e}")

    with col_status:
        last_run = st.session_state.get("last_analysis_time", "Never")
        insight_count = st.session_state.get("last_insight_count", 0)
        total_sigs = len(signals)
        st.markdown(
            f"<div style='background:#12172a;border-radius:10px;padding:12px 18px;"
            f"font-size:0.82rem;color:#aaa'>"
            f"📡 <b style='color:#eee'>{total_sigs} live signals</b> collected &nbsp;|&nbsp; "
            f"Last run: <b style='color:#eee'>{last_run}</b> &nbsp;|&nbsp; "
            f"<b style='color:#f39c12'>{insight_count} insights generated</b>"
            f"</div>",
            unsafe_allow_html=True
        )

    st.markdown("---")

    # Intent summary cards
    if focus or blind_spot or energy:
        card_col1, card_col2, card_col3 = st.columns([2, 2, 2])

        with card_col1:
            st.markdown(
                f"<div style='background:#0d1f12;border:1px solid #27ae60;border-radius:10px;"
                f"padding:16px;min-height:90px'>"
                f"<div style='color:#27ae60;font-size:0.7rem;font-weight:bold;letter-spacing:1px'>🎯 CURRENT FOCUS</div>"
                f"<div style='color:#eee;font-size:0.9rem;margin-top:8px'>{focus or 'Run analysis to discover'}</div>"
                f"</div>",
                unsafe_allow_html=True
            )

        with card_col2:
            st.markdown(
                f"<div style='background:#1f0d0d;border:1px solid #e74c3c;border-radius:10px;"
                f"padding:16px;min-height:90px'>"
                f"<div style='color:#e74c3c;font-size:0.7rem;font-weight:bold;letter-spacing:1px'>🔍 BLIND SPOT</div>"
                f"<div style='color:#eee;font-size:0.9rem;margin-top:8px'>{blind_spot or 'Run analysis to discover'}</div>"
                f"</div>",
                unsafe_allow_html=True
            )

        with card_col3:
            if energy:
                energy_items = sorted(energy.items(), key=lambda x: -x[1])
                top3 = energy_items[:3]
                bars = "".join(
                    f"<div style='display:flex;align-items:center;gap:8px;margin:3px 0'>"
                    f"<div style='font-size:0.8rem;color:#aaa;width:90px'>{k.title()}</div>"
                    f"<div style='flex:1;background:#222;border-radius:4px;height:6px'>"
                    f"<div style='width:{v}%;background:#5c6bc0;border-radius:4px;height:6px'></div>"
                    f"</div><div style='font-size:0.75rem;color:#888'>{v}%</div>"
                    f"</div>"
                    for k, v in top3
                )
                st.markdown(
                    f"<div style='background:#111827;border:1px solid #334;border-radius:10px;"
                    f"padding:16px;min-height:90px'>"
                    f"<div style='color:#888;font-size:0.7rem;font-weight:bold;letter-spacing:1px'>⚡ ENERGY ALLOCATION</div>"
                    f"<div style='margin-top:8px'>{bars}</div>"
                    f"</div>",
                    unsafe_allow_html=True
                )

        st.markdown("<br>", unsafe_allow_html=True)

    # Proactive Insights
    insights = _get_insights(uid, limit=20)
    if not insights:
        st.markdown(
            "<div style='text-align:center;padding:60px;color:#555'>"
            "<div style='font-size:3rem'>🧠</div>"
            "<div style='font-size:1.1rem;margin-top:12px'>No proactive insights yet.</div>"
            "<div style='color:#444;margin-top:8px'>Click <b>Run Proactive Analysis</b> above to generate your first briefing.</div>"
            "</div>",
            unsafe_allow_html=True
        )
        return

    st.markdown(f"### 💡 Proactive Insights ({len(insights)} active)")

    priority_order = {"critical": 0, "high": 1, "normal": 2, "low": 3}
    priority_colors = {"critical": "#e74c3c", "high": "#f39c12", "normal": "#3498db", "low": "#7f8c8d"}
    priority_icons = {"critical": "🚨", "high": "🔥", "normal": "💡", "low": "ℹ️"}

    for ins in sorted(insights, key=lambda x: priority_order.get(x["priority"], 2)):
        icon = INSIGHT_ICONS.get(ins["insight_type"], "💡")
        p_color = priority_colors.get(ins["priority"], "#3498db")
        p_icon = priority_icons.get(ins["priority"], "💡")
        age = ins["created_at"][:16] if ins["created_at"] else ""

        with st.container():
            st.markdown(
                f"<div style='background:#111827;border-left:4px solid {p_color};"
                f"border-radius:0 10px 10px 0;padding:16px 20px;margin-bottom:12px'>"
                f"<div style='display:flex;justify-content:space-between;align-items:center'>"
                f"<span style='font-size:0.7rem;color:{p_color};font-weight:bold;letter-spacing:1px'>"
                f"{p_icon} {ins['priority'].upper()} · {ins['insight_type'].upper()}</span>"
                f"<span style='font-size:0.7rem;color:#555'>{age}</span>"
                f"</div>"
                f"<div style='font-size:1rem;font-weight:600;color:#eee;margin:6px 0'>{icon} {ins['title']}</div>"
                f"<div style='font-size:0.85rem;color:#bbb;line-height:1.5'>{ins['body']}</div>"
                f"</div>",
                unsafe_allow_html=True
            )

            fb_col, _, dis_col = st.columns([3, 4, 1])
            with fb_col:
                current_fb = ins.get("feedback", "")
                fb_subcols = st.columns(3)
                with fb_subcols[0]:
                    thumbs_label = "👍 Helpful" if current_fb != "helpful" else "✅ Helpful"
                    if st.button(thumbs_label, key=f"fb_up_{ins['id']}", use_container_width=True):
                        _feedback_insight(ins["id"], "helpful")
                        st.rerun()
                with fb_subcols[1]:
                    if st.button("👎 Not helpful", key=f"fb_dn_{ins['id']}", use_container_width=True):
                        _feedback_insight(ins["id"], "not_helpful")
                        st.rerun()
                with fb_subcols[2]:
                    if st.button("✅ Done", key=f"fb_done_{ins['id']}", use_container_width=True):
                        _feedback_insight(ins["id"], "acted_on")
                        _dismiss_insight(ins["id"])
                        st.rerun()
            with dis_col:
                if st.button("✕", key=f"dismiss_{ins['id']}", help="Dismiss insight"):
                    _dismiss_insight(ins["id"])
                    st.rerun()


def _render_signals_tab(signals: list[dict]):
    """Show all collected behavioral signals."""
    st.subheader("📡 Behavioral Signal Pipeline")
    st.caption(
        "All live signals collected from across your app — finance, tasks, notes, creator pipeline, SoleOps. "
        "These feed directly into the AI's reasoning window."
    )

    if not signals:
        st.info("No signals collected. This usually means the DB tables are empty. Add data to other pages first.")
        return

    # Summary metrics
    type_counts = {}
    for s in signals:
        t = s["signal_type"]
        type_counts[t] = type_counts.get(t, 0) + 1

    metric_cols = st.columns(min(len(type_counts), 6))
    for i, (t, count) in enumerate(type_counts.items()):
        icon, _ = SIGNAL_TYPES.get(t, ("📊", "#888"))
        metric_cols[i % len(metric_cols)].metric(f"{icon} {t.title()}", count)

    st.markdown("---")

    # Filter by type
    all_types = ["All"] + list(type_counts.keys())
    filter_col, weight_col = st.columns([2, 2])
    with filter_col:
        selected_type = st.selectbox("Filter by signal type", all_types, key="signal_filter")
    with weight_col:
        min_weight = st.slider("Min signal weight", 0.0, 3.0, 0.0, 0.1, key="signal_weight_filter")

    filtered = [s for s in signals
                if (selected_type == "All" or s["signal_type"] == selected_type)
                and s.get("weight", 1.0) >= min_weight]

    filtered_sorted = sorted(filtered, key=lambda x: -x.get("weight", 1.0))

    st.markdown(f"**{len(filtered_sorted)} signals** (sorted by weight ↓)")

    for s in filtered_sorted:
        icon, color = SIGNAL_TYPES.get(s["signal_type"], ("📊", "#888"))
        weight = s.get("weight", 1.0)
        weight_bar = min(100, int(weight / 3 * 100))

        st.markdown(
            f"<div style='background:#0d1117;border:1px solid #222;border-radius:8px;"
            f"padding:10px 16px;margin-bottom:6px;display:flex;align-items:center;gap:12px'>"
            f"<span style='font-size:1.2rem'>{icon}</span>"
            f"<div style='flex:1'>"
            f"<div style='color:#eee;font-size:0.85rem'>{s['label']}</div>"
            f"<div style='color:#555;font-size:0.72rem;margin-top:2px'>Source: {s['source']}</div>"
            f"</div>"
            f"<div style='text-align:right;min-width:60px'>"
            f"<div style='font-size:0.72rem;color:{color};font-weight:bold'>w: {weight:.1f}</div>"
            f"<div style='width:50px;background:#1a1a2e;border-radius:3px;height:4px;margin-top:3px'>"
            f"<div style='width:{weight_bar}%;background:{color};border-radius:3px;height:4px'></div>"
            f"</div>"
            f"</div>"
            f"</div>",
            unsafe_allow_html=True
        )

    st.markdown("---")
    st.markdown("### 🔍 Signal Details (JSON)")
    if st.checkbox("Show raw signal data", key="show_raw_signals"):
        df = pd.DataFrame([{
            "type": s["signal_type"],
            "source": s["source"],
            "label": s["label"],
            "value": s.get("value", 0),
            "weight": s.get("weight", 1.0),
        } for s in filtered_sorted])
        st.dataframe(df, use_container_width=True, hide_index=True)


def _render_context_tab(uid: int):
    """Manual context injection — add notes that feed into AI's window."""
    st.subheader("🧩 Inject Context")
    st.caption(
        "Add anything the AI should know that isn't captured automatically: "
        "your current mood, a project you just kicked off, a constraint, a goal, a life event."
    )

    with st.form("inject_context_form", clear_on_submit=True):
        ctx_text = st.text_area(
            "What should the AI know right now?",
            placeholder="e.g. 'I'm preparing for my quarterly review at Visa next week' or "
                        "'Just closed a big SoleOps deal — feeling momentum' or "
                        "'Taking a break from creator work this week to focus on homelab'",
            height=100,
            key="ctx_input",
        )
        pinned = st.checkbox("📌 Pin this context (higher signal weight)", value=False, key="ctx_pin")
        submitted = st.form_submit_button("➕ Inject Context", type="primary", use_container_width=True)

        if submitted and ctx_text.strip():
            conn = get_conn()
            execute(conn, f"""
                INSERT INTO intent_context_notes (user_id, content, pinned)
                VALUES ({PH},{PH},{PH})
            """, (uid, ctx_text.strip(), 1 if pinned else 0))
            conn.commit()
            conn.close()
            st.success("✅ Context injected — will appear in next analysis!")
            st.rerun()
        elif submitted:
            st.error("Please enter some context text.")

    st.markdown("---")
    st.markdown("### 📋 Active Context Notes")

    conn = get_conn()
    try:
        notes = execute(conn, f"""
            SELECT id, content, pinned, created_at FROM intent_context_notes
            WHERE user_id = {PH}
            ORDER BY pinned DESC, created_at DESC
        """, (uid,)).fetchall()
    except Exception:
        notes = []
    finally:
        conn.close()

    if not notes:
        st.info("No context notes yet. Add one above to teach the AI about your current situation.")
        return

    for row in notes:
        nid, content, pinned, created = row
        pin_icon = "📌" if pinned else "🔹"
        with st.expander(f"{pin_icon} {content[:70]}  |  {created[:10]}"):
            st.text(content)
            cols = st.columns([1, 1, 4])
            with cols[0]:
                pin_label = "📌 Pinned" if pinned else "📌 Pin"
                if st.button(pin_label, key=f"pin_ctx_{nid}"):
                    conn = get_conn()
                    execute(conn, f"UPDATE intent_context_notes SET pinned = {PH} WHERE id = {PH}",
                            (0 if pinned else 1, nid))
                    conn.commit(); conn.close(); st.rerun()
            with cols[1]:
                if st.button("🗑️ Delete", key=f"del_ctx_{nid}"):
                    conn = get_conn()
                    execute(conn, f"DELETE FROM intent_context_notes WHERE id = {PH}", (nid,))
                    conn.commit(); conn.close(); st.rerun()


def _render_profile_tab(uid: int, signals: list[dict]):
    """User personalization profile — learned patterns and inferred identity."""
    st.subheader("👤 Intent Profile")
    st.caption(
        "Your AI-maintained profile — built automatically from behavioral signals over time. "
        "The more you use the app, the sharper this gets."
    )

    col_update, col_info = st.columns([2, 3])
    with col_update:
        if st.button("🔄 Update Profile from Signals", type="primary",
                     use_container_width=True, key="btn_update_profile"):
            api_key = _get_api_key()
            if not api_key:
                st.error("No Claude API key. Add it in ⚙️ Settings.")
            else:
                with st.spinner("Updating profile..."):
                    try:
                        profile = _get_profile(uid)
                        result = _run_intent_update(signals, profile, uid)
                        st.success(result)
                        st.rerun()
                    except Exception as e:
                        st.error(f"Error: {e}")
    with col_info:
        st.caption(
            "Profile updates run automatically when you run Proactive Analysis. "
            "You can also force-update here to get fresh profile data from the current signals."
        )

    st.markdown("---")

    profile = _get_profile(uid)

    if not profile:
        st.info(
            "No profile data yet. Run **Proactive Analysis** on the Dashboard tab first. "
            "The AI will start building your profile automatically."
        )
        return

    profile_sections = {
        "Focus & Goals": [
            "current_focus", "primary_income_focus", "top_productivity_area",
            "biggest_bottleneck", "estimated_weekly_bandwidth"
        ],
        "Business & Creative": [
            "creative_pipeline_health", "soleops_momentum"
        ],
        "Financial Health": [
            "financial_health_trend"
        ],
        "AI Observations": [
            "latest_blind_spot"
        ],
    }

    for section, keys in profile_sections.items():
        section_items = [(k, profile[k]) for k in keys if k in profile]
        if not section_items:
            continue

        st.markdown(f"#### {section}")
        for key, data in section_items:
            key_label = key.replace("_", " ").title()
            confidence = data["confidence"]
            updated = data["updated_at"][:10] if data["updated_at"] else ""
            conf_color = "#27ae60" if confidence >= 0.8 else ("#f39c12" if confidence >= 0.6 else "#e74c3c")

            st.markdown(
                f"<div style='background:#0d1117;border-radius:8px;padding:12px 16px;margin-bottom:8px'>"
                f"<div style='display:flex;justify-content:space-between;align-items:flex-start'>"
                f"<div>"
                f"<span style='color:#888;font-size:0.7rem;text-transform:uppercase;letter-spacing:0.5px'>"
                f"{key_label}</span>"
                f"<div style='color:#eee;font-size:0.9rem;margin-top:4px'>{data['value']}</div>"
                f"</div>"
                f"<div style='text-align:right'>"
                f"<span style='color:{conf_color};font-size:0.7rem'>{confidence:.0%} confident</span><br>"
                f"<span style='color:#444;font-size:0.65rem'>{updated}</span>"
                f"</div>"
                f"</div>"
                f"</div>",
                unsafe_allow_html=True
            )

    st.markdown("---")
    st.markdown("#### ✏️ Manual Profile Override")
    st.caption("Add or update any profile key manually.")

    with st.form("profile_manual_form", clear_on_submit=True):
        mpcol1, mpcol2 = st.columns(2)
        with mpcol1:
            mp_key = st.text_input("Profile key", placeholder="e.g. primary_goal", key="mp_key_input")
            mp_value = st.text_input("Value", placeholder="e.g. Pay off student loans by Q4", key="mp_val_input")
        with mpcol2:
            mp_confidence = st.slider("Confidence", 0.0, 1.0, 1.0, 0.05, key="mp_conf")
            st.markdown("<br>", unsafe_allow_html=True)
            mp_submit = st.form_submit_button("💾 Save to Profile", use_container_width=True)

        if mp_submit and mp_key.strip() and mp_value.strip():
            _set_profile_key(uid, mp_key.strip().lower().replace(" ", "_"), mp_value.strip(), mp_confidence)
            st.success(f"Profile updated: {mp_key}")
            st.rerun()

    # Delete profile keys
    if profile:
        st.markdown("#### 🗑️ Remove Profile Keys")
        keys_to_delete = st.multiselect(
            "Select keys to remove",
            options=list(profile.keys()),
            key="del_profile_keys"
        )
        if keys_to_delete and st.button("🗑️ Remove Selected Keys", key="btn_del_profile"):
            conn = get_conn()
            for k in keys_to_delete:
                execute(conn, f"""
                    DELETE FROM intent_profile WHERE user_id = {PH} AND key = {PH}
                """, (uid, k))
            conn.commit(); conn.close()
            st.success(f"Removed {len(keys_to_delete)} key(s).")
            st.rerun()


def _render_history_tab(uid: int):
    """Insight history — all generated insights with feedback."""
    st.subheader("📜 Insight History")

    conn = get_conn()
    try:
        all_insights = execute(conn, f"""
            SELECT id, insight_type, title, body, priority, feedback, dismissed, created_at
            FROM proactive_insights
            WHERE user_id = {PH}
            ORDER BY created_at DESC
            LIMIT 100
        """, (uid,)).fetchall()
    except Exception:
        all_insights = []
    finally:
        conn.close()

    if not all_insights:
        st.info("No insight history yet. Run Proactive Analysis from the Dashboard tab.")
        return

    # Summary stats
    total = len(all_insights)
    helpful = sum(1 for r in all_insights if r[5] == "helpful")
    acted_on = sum(1 for r in all_insights if r[5] == "acted_on")
    dismissed = sum(1 for r in all_insights if r[6] == 1)

    mc1, mc2, mc3, mc4 = st.columns(4)
    mc1.metric("Total Insights", total)
    mc2.metric("👍 Helpful", helpful)
    mc3.metric("✅ Acted On", acted_on)
    mc4.metric("✕ Dismissed", dismissed)

    st.markdown("---")

    # Filter
    show_dismissed = st.checkbox("Show dismissed insights", value=False, key="show_dismissed")
    filter_type = st.selectbox(
        "Filter by type",
        ["All", "alert", "focus", "pattern", "opportunity", "reminder", "financial", "creative", "career"],
        key="hist_type_filter"
    )

    priority_colors = {"critical": "#e74c3c", "high": "#f39c12", "normal": "#3498db", "low": "#7f8c8d"}
    feedback_badges = {
        "helpful":     "👍 Helpful",
        "not_helpful": "👎 Not helpful",
        "acted_on":    "✅ Acted on",
        None:          "",
        "":            "",
    }

    for row in all_insights:
        ins_id, ins_type, title, body, priority, feedback, is_dismissed, created_at = row
        if is_dismissed and not show_dismissed:
            continue
        if filter_type != "All" and ins_type != filter_type:
            continue

        icon = INSIGHT_ICONS.get(ins_type, "💡")
        p_color = priority_colors.get(priority, "#3498db")
        fb_badge = feedback_badges.get(feedback, "")
        dim = "opacity:0.5;" if is_dismissed else ""

        with st.expander(f"{icon} {title[:70]}  |  {created_at[:16]}  {fb_badge}"):
            st.markdown(
                f"<div style='{dim}background:#0d1117;border-left:3px solid {p_color};"
                f"padding:12px;border-radius:0 8px 8px 0'>"
                f"<div style='color:{p_color};font-size:0.7rem;font-weight:bold'>{priority.upper()} · {ins_type.upper()}</div>"
                f"<div style='color:#bbb;margin-top:6px;font-size:0.85rem'>{body}</div>"
                f"</div>",
                unsafe_allow_html=True
            )
            if fb_badge:
                st.caption(f"Feedback: {fb_badge}")

    # Clear all history button
    st.markdown("---")
    if st.button("🗑️ Clear All Insight History", key="btn_clear_hist"):
        conn = get_conn()
        execute(conn, f"DELETE FROM proactive_insights WHERE user_id = {PH}", (uid,))
        conn.commit(); conn.close()
        st.success("History cleared.")
        st.rerun()


def _render_settings_tab(uid: int):
    """Settings for the Proactive AI engine."""
    st.subheader("⚙️ Settings")

    # API key
    st.markdown("#### 🔑 Claude API Key")
    api_key = _get_api_key()
    if api_key:
        st.success(f"✅ Claude API key loaded ({api_key[:12]}...)")
        if st.button("🔄 Change API Key", key="change_key_btn"):
            st.session_state["show_key_input"] = True

    if not api_key or st.session_state.get("show_key_input"):
        new_key = st.text_input(
            "Claude API Key",
            type="password",
            placeholder="sk-ant-api03-...",
            key="settings_api_key_input"
        )
        if new_key and new_key.startswith("sk-ant-"):
            st.session_state["api_key"] = new_key
            set_setting("anthropic_api_key", new_key)
            st.session_state.pop("show_key_input", None)
            st.success("✅ API key saved!")
            st.rerun()

    st.markdown("---")
    st.markdown("#### 🎛️ Signal Collection Settings")

    sig_settings = {
        "collect_finance": ("💰 Finance signals",          True),
        "collect_todos":   ("✅ Task / Todo signals",       True),
        "collect_notes":   ("📝 Notes signals",             True),
        "collect_creator": ("🎬 Creator pipeline signals",  True),
        "collect_soleops": ("👟 SoleOps inventory signals", True),
    }

    for key, (label, default) in sig_settings.items():
        current_val = get_setting(f"intent_{key}", "true").lower() == "true"
        new_val = st.checkbox(label, value=current_val, key=f"setting_{key}")
        if new_val != current_val:
            set_setting(f"intent_{key}", "true" if new_val else "false")

    st.markdown("---")
    st.markdown("#### 🗑️ Data Management")

    col_a, col_b, col_c = st.columns(3)
    with col_a:
        if st.button("🗑️ Clear All Insights", key="clear_insights_btn", use_container_width=True):
            conn = get_conn()
            execute(conn, f"DELETE FROM proactive_insights WHERE user_id = {PH}", (uid,))
            conn.commit(); conn.close()
            st.success("Insights cleared.")
            st.rerun()
    with col_b:
        if st.button("🗑️ Clear Context Notes", key="clear_ctx_btn", use_container_width=True):
            conn = get_conn()
            execute(conn, f"DELETE FROM intent_context_notes WHERE user_id = {PH}", (uid,))
            conn.commit(); conn.close()
            st.success("Context notes cleared.")
            st.rerun()
    with col_c:
        if st.button("🗑️ Reset Profile", key="reset_profile_btn", use_container_width=True):
            conn = get_conn()
            execute(conn, f"DELETE FROM intent_profile WHERE user_id = {PH}", (uid,))
            conn.commit(); conn.close()
            st.success("Profile reset.")
            st.rerun()

    st.markdown("---")
    st.markdown("#### 📖 About This Page")
    st.markdown("""
**Proactive AI / Intent Engine** — Page 147

This page implements the vision from a conversation about the future of human-AI interaction:

> *"The real frontier isn't translation — it's compression of the expression layer. Fewer words, faster context, smarter inference."*

Instead of waiting for you to type a prompt, this engine:

1. **Collects behavioral signals** from every corner of your app (finance, tasks, notes, creator pipeline, resale business)
2. **Builds a personalization layer** — a user model that learns your patterns, goals, and constraints over time
3. **Feeds it all as structured context** into Claude's reasoning window
4. **Returns proactive insights** — surfacing what you probably need right now, before you ask

This is a practical implementation of *passive intent inference* — predicting what you need from behavioral patterns and context, not from a typed prompt.

**Stack:** Python · Streamlit · SQLite/PostgreSQL · Anthropic Claude claude-opus-4-5
""")


# ── Main Layout ───────────────────────────────────────────────────────────────

user = st.session_state.get("user", {})
uid = user.get("id", 0)

st.title("🧠 Proactive AI Engine")
st.caption(
    "Behavioral signals → intent inference → proactive insights. "
    "The AI learns your patterns and surfaces what you need before you ask."
)

# Collect all live signals upfront (fast — all DB reads, no AI)
live_signals = _collect_all_signals(uid)

tab_dashboard, tab_signals, tab_context, tab_profile, tab_history, tab_settings = st.tabs([
    "🧠 Dashboard",
    "📡 Signal Pipeline",
    "🧩 Inject Context",
    "👤 My Profile",
    "📜 History",
    "⚙️ Settings",
])

with tab_dashboard:
    _render_dashboard_tab(uid, live_signals)

with tab_signals:
    _render_signals_tab(live_signals)

with tab_context:
    _render_context_tab(uid)

with tab_profile:
    _render_profile_tab(uid, live_signals)

with tab_history:
    _render_history_tab(uid)

with tab_settings:
    _render_settings_tab(uid)
